channels:
  - defaults

dependencies:
  - python=3.8
  - pip
  - setuptools_scm
  - toml

  # Documentation
  - sphinx
  - sphinx-autoapi
  - sphinx-copybutton
  - sphinx-panels
  - pydata-sphinx-theme>=0.3.0

  - pip:
      - ../
